name: Build

on:
  workflow_dispatch:

jobs:
  build-standard:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            os: windows-latest
          - rid: win-arm64
            os: windows-11-arm
          
          - rid: linux-x64
            os: ubuntu-22.04
          - rid: linux-arm64
            os: ubuntu-22.04-arm

          - rid: osx-x64
            os: macos-26-intel
          - rid: osx-arm64
            os: macos-26

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install NativeAOT Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang zlib1g-dev

      - name: Publish DumbVersionCreator
        run: dotnet publish DumbVersionCreator/DumbVersionCreator.csproj -c Release -r ${{ matrix.rid }} -o ./output/Creator

      - name: Publish DumbVersionPatcher
        run: dotnet publish DumbVersionPatcher/DumbVersionPatcher.csproj -c Release -r ${{ matrix.rid }} -o ./output/Patcher

      - name: Stage Unix Binaries
        if: runner.os != 'Windows'
        run: |
          mkdir -p ./release
          cp ./output/Creator/DumbVersionCreator ./release/
          cp ./output/Patcher/DumbVersionPatcher ./release/

      - name: Stage Windows Binaries
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path ./release/
          Copy-Item ./output/Creator/DumbVersionCreator.exe ./release/
          Copy-Item ./output/Patcher/DumbVersionPatcher.exe ./release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersion-${{ matrix.rid }}
          path: ./release/*
          retention-days: 7

  build-musl:
    name: Build linux-musl-x64
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0-alpine-aot

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Publish DumbVersionCreator
        run: dotnet publish DumbVersionCreator/DumbVersionCreator.csproj -c Release -r linux-musl-x64 -o ./output/Creator

      - name: Publish DumbVersionPatcher
        run: dotnet publish DumbVersionPatcher/DumbVersionPatcher.csproj -c Release -r linux-musl-x64 -o ./output/Patcher

      - name: Stage Musl Binaries
        run: |
          mkdir -p ./release
          cp ./output/Creator/DumbVersionCreator ./release
          cp ./output/Patcher/DumbVersionPatcher ./release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: DumbVersion-linux-musl-x64
          path: ./release/*
          retention-days: 7